name: myapp2
version: 1.0.0
appVersion: 1.0.0
description: myapp2 is a JHipster based microservice application
icon: https://www.jhipster.tech/images/logo/logo-jhipster-drink-coffee.svg
keywords:
- spring
- angular
- react
- JHipster
- myapp2
home: https://www.jhipster.tech/
sources:
- https://github.com/jhipster/generator-jhipster.git
maintainers:
- name: Team JHipster
  email:
dependencies:
- name: mysql
  version: ^1.4.0
  repository: https://charts.helm.sh/stable
  condition: mysql.enabled
